name: build-docs

on:
  push:
    branches:
      - master
      - feature/docs

jobs:
  run-docfx:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Cysharp/Actions/.github/actions/checkout@main
      - uses: Cysharp/Actions/.github/actions/checkout@main
        with:
          repository: Cysharp/DocfxTemplate
          path: docs/_DocfxTemplate
      - uses: Kirbyrawr/docfx-action@db9a22c8fe1e8693a2a21be54cb0b87dfaa72cc4
        name: Docfx metadata
        with:
          args: metadata docs/docfx.json
      - uses: Kirbyrawr/docfx-action@db9a22c8fe1e8693a2a21be54cb0b87dfaa72cc4
        name: Docfx build
        with:
          args: build docs/docfx.json
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
