name: build-docs

on:
  push:
    branches:
      - master
      - feature/docs

jobs:
  run-docfx:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: Cysharp/DocfxTemplate
          path: docs/_DocfxTemplate
      - uses: Kirbyrawr/docfx-action@master
        name: Docfx metadata
        with:
          args: metadata docs/docfx.json
      - uses: Kirbyrawr/docfx-action@master
        name: Docfx build
        with:
          args: build docs/docfx.json
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
